// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: schat/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgAuthEncrptyKey struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Key     string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (m *MsgAuthEncrptyKey) Reset()         { *m = MsgAuthEncrptyKey{} }
func (m *MsgAuthEncrptyKey) String() string { return proto.CompactTextString(m) }
func (*MsgAuthEncrptyKey) ProtoMessage()    {}
func (*MsgAuthEncrptyKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5e5c2496a0ba0af, []int{0}
}
func (m *MsgAuthEncrptyKey) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAuthEncrptyKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAuthEncrptyKey.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAuthEncrptyKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAuthEncrptyKey.Merge(m, src)
}
func (m *MsgAuthEncrptyKey) XXX_Size() int {
	return m.Size()
}
func (m *MsgAuthEncrptyKey) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAuthEncrptyKey.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAuthEncrptyKey proto.InternalMessageInfo

func (m *MsgAuthEncrptyKey) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgAuthEncrptyKey) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type MsgAuthEncrptyKeyResponse struct {
	Success  bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	KeyTotal uint64 `protobuf:"varint,2,opt,name=keyTotal,proto3" json:"keyTotal,omitempty"`
}

func (m *MsgAuthEncrptyKeyResponse) Reset()         { *m = MsgAuthEncrptyKeyResponse{} }
func (m *MsgAuthEncrptyKeyResponse) String() string { return proto.CompactTextString(m) }
func (*MsgAuthEncrptyKeyResponse) ProtoMessage()    {}
func (*MsgAuthEncrptyKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5e5c2496a0ba0af, []int{1}
}
func (m *MsgAuthEncrptyKeyResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAuthEncrptyKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAuthEncrptyKeyResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAuthEncrptyKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAuthEncrptyKeyResponse.Merge(m, src)
}
func (m *MsgAuthEncrptyKeyResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgAuthEncrptyKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAuthEncrptyKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAuthEncrptyKeyResponse proto.InternalMessageInfo

func (m *MsgAuthEncrptyKeyResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *MsgAuthEncrptyKeyResponse) GetKeyTotal() uint64 {
	if m != nil {
		return m.KeyTotal
	}
	return 0
}

type MsgCreateConversation struct {
	Creator     string   `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Participant []string `protobuf:"bytes,2,rep,name=participant,proto3" json:"participant,omitempty"`
}

func (m *MsgCreateConversation) Reset()         { *m = MsgCreateConversation{} }
func (m *MsgCreateConversation) String() string { return proto.CompactTextString(m) }
func (*MsgCreateConversation) ProtoMessage()    {}
func (*MsgCreateConversation) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5e5c2496a0ba0af, []int{2}
}
func (m *MsgCreateConversation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateConversation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateConversation.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateConversation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateConversation.Merge(m, src)
}
func (m *MsgCreateConversation) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateConversation) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateConversation.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateConversation proto.InternalMessageInfo

func (m *MsgCreateConversation) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreateConversation) GetParticipant() []string {
	if m != nil {
		return m.Participant
	}
	return nil
}

type MsgCreateConversationResponse struct {
	HashParticipant []uint32 `protobuf:"varint,1,rep,packed,name=hashParticipant,proto3" json:"hashParticipant,omitempty"`
}

func (m *MsgCreateConversationResponse) Reset()         { *m = MsgCreateConversationResponse{} }
func (m *MsgCreateConversationResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateConversationResponse) ProtoMessage()    {}
func (*MsgCreateConversationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5e5c2496a0ba0af, []int{3}
}
func (m *MsgCreateConversationResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateConversationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateConversationResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateConversationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateConversationResponse.Merge(m, src)
}
func (m *MsgCreateConversationResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateConversationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateConversationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateConversationResponse proto.InternalMessageInfo

func (m *MsgCreateConversationResponse) GetHashParticipant() []uint32 {
	if m != nil {
		return m.HashParticipant
	}
	return nil
}

type MsgSendMessage struct {
	Creator         string   `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	HashParticipant []uint32 `protobuf:"varint,2,rep,packed,name=hashParticipant,proto3" json:"hashParticipant,omitempty"`
	Message         string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (m *MsgSendMessage) Reset()         { *m = MsgSendMessage{} }
func (m *MsgSendMessage) String() string { return proto.CompactTextString(m) }
func (*MsgSendMessage) ProtoMessage()    {}
func (*MsgSendMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5e5c2496a0ba0af, []int{4}
}
func (m *MsgSendMessage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSendMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSendMessage.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSendMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSendMessage.Merge(m, src)
}
func (m *MsgSendMessage) XXX_Size() int {
	return m.Size()
}
func (m *MsgSendMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSendMessage.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSendMessage proto.InternalMessageInfo

func (m *MsgSendMessage) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgSendMessage) GetHashParticipant() []uint32 {
	if m != nil {
		return m.HashParticipant
	}
	return nil
}

func (m *MsgSendMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type MsgSendMessageResponse struct {
}

func (m *MsgSendMessageResponse) Reset()         { *m = MsgSendMessageResponse{} }
func (m *MsgSendMessageResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSendMessageResponse) ProtoMessage()    {}
func (*MsgSendMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5e5c2496a0ba0af, []int{5}
}
func (m *MsgSendMessageResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSendMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSendMessageResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSendMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSendMessageResponse.Merge(m, src)
}
func (m *MsgSendMessageResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSendMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSendMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSendMessageResponse proto.InternalMessageInfo

type MsgGetConversationKey struct {
	Creator         string   `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	HashParticipant []uint32 `protobuf:"varint,2,rep,packed,name=hashParticipant,proto3" json:"hashParticipant,omitempty"`
}

func (m *MsgGetConversationKey) Reset()         { *m = MsgGetConversationKey{} }
func (m *MsgGetConversationKey) String() string { return proto.CompactTextString(m) }
func (*MsgGetConversationKey) ProtoMessage()    {}
func (*MsgGetConversationKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5e5c2496a0ba0af, []int{6}
}
func (m *MsgGetConversationKey) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgGetConversationKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgGetConversationKey.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgGetConversationKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgGetConversationKey.Merge(m, src)
}
func (m *MsgGetConversationKey) XXX_Size() int {
	return m.Size()
}
func (m *MsgGetConversationKey) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgGetConversationKey.DiscardUnknown(m)
}

var xxx_messageInfo_MsgGetConversationKey proto.InternalMessageInfo

func (m *MsgGetConversationKey) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgGetConversationKey) GetHashParticipant() []uint32 {
	if m != nil {
		return m.HashParticipant
	}
	return nil
}

type MsgGetConversationKeyResponse struct {
	EncryptKey string `protobuf:"bytes,1,opt,name=encryptKey,proto3" json:"encryptKey,omitempty"`
	Decrypt    string `protobuf:"bytes,2,opt,name=decrypt,proto3" json:"decrypt,omitempty"`
}

func (m *MsgGetConversationKeyResponse) Reset()         { *m = MsgGetConversationKeyResponse{} }
func (m *MsgGetConversationKeyResponse) String() string { return proto.CompactTextString(m) }
func (*MsgGetConversationKeyResponse) ProtoMessage()    {}
func (*MsgGetConversationKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5e5c2496a0ba0af, []int{7}
}
func (m *MsgGetConversationKeyResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgGetConversationKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgGetConversationKeyResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgGetConversationKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgGetConversationKeyResponse.Merge(m, src)
}
func (m *MsgGetConversationKeyResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgGetConversationKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgGetConversationKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgGetConversationKeyResponse proto.InternalMessageInfo

func (m *MsgGetConversationKeyResponse) GetEncryptKey() string {
	if m != nil {
		return m.EncryptKey
	}
	return ""
}

func (m *MsgGetConversationKeyResponse) GetDecrypt() string {
	if m != nil {
		return m.Decrypt
	}
	return ""
}

func init() {
	proto.RegisterType((*MsgAuthEncrptyKey)(nil), "chengyu97.schat.schat.MsgAuthEncrptyKey")
	proto.RegisterType((*MsgAuthEncrptyKeyResponse)(nil), "chengyu97.schat.schat.MsgAuthEncrptyKeyResponse")
	proto.RegisterType((*MsgCreateConversation)(nil), "chengyu97.schat.schat.MsgCreateConversation")
	proto.RegisterType((*MsgCreateConversationResponse)(nil), "chengyu97.schat.schat.MsgCreateConversationResponse")
	proto.RegisterType((*MsgSendMessage)(nil), "chengyu97.schat.schat.MsgSendMessage")
	proto.RegisterType((*MsgSendMessageResponse)(nil), "chengyu97.schat.schat.MsgSendMessageResponse")
	proto.RegisterType((*MsgGetConversationKey)(nil), "chengyu97.schat.schat.MsgGetConversationKey")
	proto.RegisterType((*MsgGetConversationKeyResponse)(nil), "chengyu97.schat.schat.MsgGetConversationKeyResponse")
}

func init() { proto.RegisterFile("schat/tx.proto", fileDescriptor_d5e5c2496a0ba0af) }

var fileDescriptor_d5e5c2496a0ba0af = []byte{
	// 458 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0x41, 0x6b, 0xd4, 0x40,
	0x14, 0xc7, 0x37, 0x1b, 0xd1, 0xf6, 0x15, 0x57, 0x0d, 0x54, 0xe2, 0x82, 0x61, 0x19, 0x10, 0x72,
	0xd0, 0xac, 0xa8, 0x50, 0x7a, 0x12, 0xbb, 0x88, 0x48, 0x09, 0x68, 0xd6, 0x4b, 0xf5, 0x34, 0x9d,
	0x3e, 0x92, 0xa5, 0xed, 0x4c, 0xc8, 0x4c, 0x64, 0xe7, 0x5b, 0xf8, 0xb1, 0x3c, 0x78, 0xe8, 0xd1,
	0xa3, 0xec, 0x7e, 0x11, 0xc9, 0x6c, 0x12, 0x62, 0x93, 0x0d, 0xeb, 0x25, 0xe4, 0xbd, 0xfc, 0xf9,
	0xbd, 0xff, 0x9b, 0xfc, 0x19, 0x18, 0x49, 0x96, 0x50, 0x35, 0x55, 0xcb, 0x20, 0xcd, 0x84, 0x12,
	0xce, 0x21, 0x4b, 0x90, 0xc7, 0x3a, 0x3f, 0x3e, 0x0a, 0xcc, 0x97, 0xcd, 0x93, 0xbc, 0x85, 0x47,
	0xa1, 0x8c, 0xdf, 0xe5, 0x2a, 0x79, 0xcf, 0x59, 0x96, 0x2a, 0x7d, 0x8a, 0xda, 0x71, 0xe1, 0x1e,
	0xcb, 0x90, 0x2a, 0x91, 0xb9, 0xd6, 0xc4, 0xf2, 0xf7, 0xa3, 0xaa, 0x74, 0x1e, 0x82, 0x7d, 0x89,
	0xda, 0x1d, 0x9a, 0x6e, 0xf1, 0x4a, 0x3e, 0xc3, 0x93, 0x16, 0x20, 0x42, 0x99, 0x0a, 0x2e, 0xb1,
	0x00, 0xc9, 0x9c, 0x31, 0x94, 0xd2, 0x80, 0xf6, 0xa2, 0xaa, 0x74, 0xc6, 0xb0, 0x77, 0x89, 0xfa,
	0x8b, 0x50, 0xf4, 0xca, 0xd0, 0xee, 0x44, 0x75, 0x4d, 0xe6, 0x70, 0x18, 0xca, 0x78, 0x56, 0x8c,
	0xc4, 0x99, 0xe0, 0xdf, 0x31, 0x93, 0x54, 0x2d, 0x04, 0xef, 0xf1, 0x35, 0x81, 0x83, 0x94, 0x66,
	0x6a, 0xc1, 0x16, 0x29, 0xe5, 0xca, 0x1d, 0x4e, 0x6c, 0x7f, 0x3f, 0x6a, 0xb6, 0xc8, 0x47, 0x78,
	0xda, 0x09, 0xad, 0xbd, 0xfa, 0xf0, 0x20, 0xa1, 0x32, 0xf9, 0xd4, 0xc0, 0x58, 0x13, 0xdb, 0xbf,
	0x1f, 0xdd, 0x6e, 0x13, 0x0e, 0xa3, 0x50, 0xc6, 0x73, 0xe4, 0x17, 0x21, 0x4a, 0x49, 0x63, 0xec,
	0x31, 0xd6, 0x41, 0x1d, 0x76, 0x52, 0x0b, 0xc6, 0xf5, 0x06, 0xe7, 0xda, 0x1b, 0x46, 0x59, 0x12,
	0x17, 0x1e, 0xff, 0x3b, 0xaf, 0xf2, 0x4c, 0xbe, 0x99, 0x93, 0xfa, 0x80, 0xaa, 0xb9, 0x51, 0xff,
	0x1f, 0xdc, 0xd9, 0x10, 0x39, 0x33, 0x27, 0xd6, 0x86, 0xd7, 0x27, 0xe6, 0x01, 0x20, 0x67, 0x99,
	0x4e, 0xd5, 0x29, 0xea, 0x72, 0x4e, 0xa3, 0x53, 0x98, 0xb8, 0x40, 0x53, 0x95, 0x81, 0xa9, 0xca,
	0x57, 0xbf, 0x6c, 0xb0, 0x43, 0x19, 0x3b, 0x57, 0x30, 0xba, 0x15, 0x3d, 0x3f, 0xe8, 0xcc, 0x69,
	0xd0, 0xca, 0xd8, 0xf8, 0xe5, 0xae, 0xca, 0xda, 0xef, 0x12, 0x9c, 0x8e, 0x50, 0x3d, 0xdf, 0xce,
	0x69, 0xab, 0xc7, 0x6f, 0xfe, 0x47, 0x5d, 0x4f, 0x66, 0x70, 0xd0, 0x8c, 0xcb, 0xb3, 0xed, 0x90,
	0x86, 0x6c, 0xfc, 0x62, 0x27, 0x59, 0x73, 0xbd, 0x8e, 0x24, 0xf4, 0xac, 0xd7, 0x56, 0xf7, 0xad,
	0xb7, 0x3d, 0x08, 0x27, 0x27, 0x3f, 0x57, 0x9e, 0x75, 0xb3, 0xf2, 0xac, 0x3f, 0x2b, 0xcf, 0xfa,
	0xb1, 0xf6, 0x06, 0x37, 0x6b, 0x6f, 0xf0, 0x7b, 0xed, 0x0d, 0xbe, 0xfa, 0xf1, 0x42, 0x25, 0xf9,
	0x79, 0xc0, 0xc4, 0xf5, 0x74, 0x56, 0x90, 0xcf, 0xf2, 0xe3, 0xa3, 0xe9, 0x7c, 0x56, 0x5c, 0x4d,
	0xcb, 0x69, 0x79, 0x45, 0xe9, 0x14, 0xe5, 0xf9, 0x5d, 0x73, 0x4d, 0xbd, 0xfe, 0x1b, 0x00, 0x00,
	0xff, 0xff, 0x1e, 0xa6, 0xc6, 0x40, 0xb8, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	AuthEncrptyKey(ctx context.Context, in *MsgAuthEncrptyKey, opts ...grpc.CallOption) (*MsgAuthEncrptyKeyResponse, error)
	CreateConversation(ctx context.Context, in *MsgCreateConversation, opts ...grpc.CallOption) (*MsgCreateConversationResponse, error)
	SendMessage(ctx context.Context, in *MsgSendMessage, opts ...grpc.CallOption) (*MsgSendMessageResponse, error)
	GetConversationKey(ctx context.Context, in *MsgGetConversationKey, opts ...grpc.CallOption) (*MsgGetConversationKeyResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) AuthEncrptyKey(ctx context.Context, in *MsgAuthEncrptyKey, opts ...grpc.CallOption) (*MsgAuthEncrptyKeyResponse, error) {
	out := new(MsgAuthEncrptyKeyResponse)
	err := c.cc.Invoke(ctx, "/chengyu97.schat.schat.Msg/AuthEncrptyKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreateConversation(ctx context.Context, in *MsgCreateConversation, opts ...grpc.CallOption) (*MsgCreateConversationResponse, error) {
	out := new(MsgCreateConversationResponse)
	err := c.cc.Invoke(ctx, "/chengyu97.schat.schat.Msg/CreateConversation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SendMessage(ctx context.Context, in *MsgSendMessage, opts ...grpc.CallOption) (*MsgSendMessageResponse, error) {
	out := new(MsgSendMessageResponse)
	err := c.cc.Invoke(ctx, "/chengyu97.schat.schat.Msg/SendMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) GetConversationKey(ctx context.Context, in *MsgGetConversationKey, opts ...grpc.CallOption) (*MsgGetConversationKeyResponse, error) {
	out := new(MsgGetConversationKeyResponse)
	err := c.cc.Invoke(ctx, "/chengyu97.schat.schat.Msg/GetConversationKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	AuthEncrptyKey(context.Context, *MsgAuthEncrptyKey) (*MsgAuthEncrptyKeyResponse, error)
	CreateConversation(context.Context, *MsgCreateConversation) (*MsgCreateConversationResponse, error)
	SendMessage(context.Context, *MsgSendMessage) (*MsgSendMessageResponse, error)
	GetConversationKey(context.Context, *MsgGetConversationKey) (*MsgGetConversationKeyResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) AuthEncrptyKey(ctx context.Context, req *MsgAuthEncrptyKey) (*MsgAuthEncrptyKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthEncrptyKey not implemented")
}
func (*UnimplementedMsgServer) CreateConversation(ctx context.Context, req *MsgCreateConversation) (*MsgCreateConversationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateConversation not implemented")
}
func (*UnimplementedMsgServer) SendMessage(ctx context.Context, req *MsgSendMessage) (*MsgSendMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (*UnimplementedMsgServer) GetConversationKey(ctx context.Context, req *MsgGetConversationKey) (*MsgGetConversationKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConversationKey not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_AuthEncrptyKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAuthEncrptyKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).AuthEncrptyKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chengyu97.schat.schat.Msg/AuthEncrptyKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).AuthEncrptyKey(ctx, req.(*MsgAuthEncrptyKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreateConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateConversation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chengyu97.schat.schat.Msg/CreateConversation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateConversation(ctx, req.(*MsgCreateConversation))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSendMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chengyu97.schat.schat.Msg/SendMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SendMessage(ctx, req.(*MsgSendMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_GetConversationKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgGetConversationKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).GetConversationKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chengyu97.schat.schat.Msg/GetConversationKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).GetConversationKey(ctx, req.(*MsgGetConversationKey))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chengyu97.schat.schat.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AuthEncrptyKey",
			Handler:    _Msg_AuthEncrptyKey_Handler,
		},
		{
			MethodName: "CreateConversation",
			Handler:    _Msg_CreateConversation_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _Msg_SendMessage_Handler,
		},
		{
			MethodName: "GetConversationKey",
			Handler:    _Msg_GetConversationKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "schat/tx.proto",
}

func (m *MsgAuthEncrptyKey) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAuthEncrptyKey) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAuthEncrptyKey) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Key) > 0 {
		i -= len(m.Key)
		copy(dAtA[i:], m.Key)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Key)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgAuthEncrptyKeyResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAuthEncrptyKeyResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAuthEncrptyKeyResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.KeyTotal != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.KeyTotal))
		i--
		dAtA[i] = 0x10
	}
	if m.Success {
		i--
		if m.Success {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateConversation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateConversation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateConversation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Participant) > 0 {
		for iNdEx := len(m.Participant) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Participant[iNdEx])
			copy(dAtA[i:], m.Participant[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.Participant[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateConversationResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateConversationResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateConversationResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.HashParticipant) > 0 {
		dAtA2 := make([]byte, len(m.HashParticipant)*10)
		var j1 int
		for _, num := range m.HashParticipant {
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		i -= j1
		copy(dAtA[i:], dAtA2[:j1])
		i = encodeVarintTx(dAtA, i, uint64(j1))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSendMessage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSendMessage) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSendMessage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Message) > 0 {
		i -= len(m.Message)
		copy(dAtA[i:], m.Message)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Message)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.HashParticipant) > 0 {
		dAtA4 := make([]byte, len(m.HashParticipant)*10)
		var j3 int
		for _, num := range m.HashParticipant {
			for num >= 1<<7 {
				dAtA4[j3] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j3++
			}
			dAtA4[j3] = uint8(num)
			j3++
		}
		i -= j3
		copy(dAtA[i:], dAtA4[:j3])
		i = encodeVarintTx(dAtA, i, uint64(j3))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSendMessageResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSendMessageResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSendMessageResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgGetConversationKey) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgGetConversationKey) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgGetConversationKey) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.HashParticipant) > 0 {
		dAtA6 := make([]byte, len(m.HashParticipant)*10)
		var j5 int
		for _, num := range m.HashParticipant {
			for num >= 1<<7 {
				dAtA6[j5] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j5++
			}
			dAtA6[j5] = uint8(num)
			j5++
		}
		i -= j5
		copy(dAtA[i:], dAtA6[:j5])
		i = encodeVarintTx(dAtA, i, uint64(j5))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgGetConversationKeyResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgGetConversationKeyResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgGetConversationKeyResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Decrypt) > 0 {
		i -= len(m.Decrypt)
		copy(dAtA[i:], m.Decrypt)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Decrypt)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.EncryptKey) > 0 {
		i -= len(m.EncryptKey)
		copy(dAtA[i:], m.EncryptKey)
		i = encodeVarintTx(dAtA, i, uint64(len(m.EncryptKey)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgAuthEncrptyKey) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Key)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgAuthEncrptyKeyResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Success {
		n += 2
	}
	if m.KeyTotal != 0 {
		n += 1 + sovTx(uint64(m.KeyTotal))
	}
	return n
}

func (m *MsgCreateConversation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Participant) > 0 {
		for _, s := range m.Participant {
			l = len(s)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgCreateConversationResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.HashParticipant) > 0 {
		l = 0
		for _, e := range m.HashParticipant {
			l += sovTx(uint64(e))
		}
		n += 1 + sovTx(uint64(l)) + l
	}
	return n
}

func (m *MsgSendMessage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.HashParticipant) > 0 {
		l = 0
		for _, e := range m.HashParticipant {
			l += sovTx(uint64(e))
		}
		n += 1 + sovTx(uint64(l)) + l
	}
	l = len(m.Message)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSendMessageResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgGetConversationKey) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.HashParticipant) > 0 {
		l = 0
		for _, e := range m.HashParticipant {
			l += sovTx(uint64(e))
		}
		n += 1 + sovTx(uint64(l)) + l
	}
	return n
}

func (m *MsgGetConversationKeyResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.EncryptKey)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Decrypt)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgAuthEncrptyKey) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAuthEncrptyKey: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAuthEncrptyKey: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Key = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAuthEncrptyKeyResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAuthEncrptyKeyResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAuthEncrptyKeyResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Success", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Success = bool(v != 0)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeyTotal", wireType)
			}
			m.KeyTotal = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.KeyTotal |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateConversation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateConversation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateConversation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Participant", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Participant = append(m.Participant, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateConversationResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateConversationResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateConversationResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType == 0 {
				var v uint32
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTx
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint32(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.HashParticipant = append(m.HashParticipant, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTx
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthTx
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthTx
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.HashParticipant) == 0 {
					m.HashParticipant = make([]uint32, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint32
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowTx
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint32(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.HashParticipant = append(m.HashParticipant, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field HashParticipant", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSendMessage) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSendMessage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSendMessage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType == 0 {
				var v uint32
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTx
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint32(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.HashParticipant = append(m.HashParticipant, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTx
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthTx
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthTx
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.HashParticipant) == 0 {
					m.HashParticipant = make([]uint32, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint32
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowTx
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint32(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.HashParticipant = append(m.HashParticipant, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field HashParticipant", wireType)
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Message", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Message = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSendMessageResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSendMessageResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSendMessageResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgGetConversationKey) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgGetConversationKey: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgGetConversationKey: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType == 0 {
				var v uint32
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTx
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint32(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.HashParticipant = append(m.HashParticipant, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTx
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthTx
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthTx
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.HashParticipant) == 0 {
					m.HashParticipant = make([]uint32, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint32
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowTx
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint32(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.HashParticipant = append(m.HashParticipant, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field HashParticipant", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgGetConversationKeyResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgGetConversationKeyResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgGetConversationKeyResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EncryptKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EncryptKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Decrypt", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Decrypt = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
